version: '3'
services:
  account:
    build: .
    volumes:
    - ./config.json:/app/config.json
  proxy:
    image: nginx:alpine
    ports:
    - 80:80
    volumes:
    - ./proxy.conf:/etc/nginx/conf.d/default.conf