version: 2.1
orbs:
  docker-publish: circleci/docker-publish@0.1.7
workflows:
  buildpush:
    jobs:
      - docker-publish/publish:
          filters:
            branches:
              only: master
      - docker-publish/publish:
          deploy: false
          filters:
            branches:
              ignore: master